name: CoolAppWorkflow

on: workflow_dispatch

jobs:
  test:
    name: Тестирование проекта
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Запуск тестов
      run: dotnet test /app/CoolAppTest/CoolAppTest.csproj
